# Generated by Django 2.1.7 on 2019-03-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190304_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language_id',
            field=models.ForeignKey(default='English', on_delete=django.db.models.deletion.PROTECT, to='book.Language'),
            preserve_default=False,
        ),
    ]
