# Generated by Django 2.1.7 on 2019-03-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190305_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>'),
        ),
    ]
